import { prisma } from '../../app';
import { logger } from '../utils/logger/logger';

const loanSeedData = [
  // ── PERSONAL_LOAN (14 entries) ──
  {
    bankName: 'BRAC_BANK_PLC' as const,
    amount: '500000',
    processingFee: '1.5',
    interestRate: '12.99',
    monthlyEmi: '16750',
    totalAmount: '603000',
    eligibleLoan: '500000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '5,00,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '15,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 23-60',
      offer: 'Competitive interest rate starting from 12.99%',
      minimumIncome: 30000,
      minimumExperience: 1,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1.5% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'DUTCH_BANGLA_BANK_PLC' as const,
    amount: '300000',
    processingFee: '1.0',
    interestRate: '11.50',
    monthlyEmi: '9870',
    totalAmount: '355320',
    eligibleLoan: '300000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '3,00,000 BDT',
      minimumAmount: '30,000 BDT',
      maximumAmount: '10,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '6 Months',
      maximumYear: '4 Years',
    },
    eligibility: {
      condition: 'Salaried professionals, age 21-60',
      offer: 'Lowest EMI starting from 9,870 BDT/month',
      minimumIncome: 25000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'CITY_BANK_PLC' as const,
    amount: '800000',
    processingFee: '1.25',
    interestRate: '13.50',
    monthlyEmi: '27120',
    totalAmount: '976320',
    eligibleLoan: '800000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '8,00,000 BDT',
      minimumAmount: '1,00,000 BDT',
      maximumAmount: '25,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Salaried or self-employed, age 23-58',
      offer: 'Quick approval within 24 hours',
      minimumIncome: 50000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1.25% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'EASTERN_BANK_PLC' as const,
    amount: '600000',
    processingFee: '1.0',
    interestRate: '12.50',
    monthlyEmi: '20040',
    totalAmount: '721440',
    eligibleLoan: '600000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '6,00,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '20,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried professionals with 1+ year experience',
      offer: 'Zero collateral up to 20 lakh',
      minimumIncome: 35000,
      minimumExperience: 1,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'UNITED_COMMERCIAL_BANK_PLC' as const,
    amount: '400000',
    processingFee: '1.5',
    interestRate: '13.00',
    monthlyEmi: '13480',
    totalAmount: '485280',
    eligibleLoan: '400000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '4,00,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '12,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Bangladeshi nationals, age 21-57',
      offer: 'Minimal documentation required',
      minimumIncome: 25000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1.5% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'PRIME_BANK_PLC' as const,
    amount: '700000',
    processingFee: '1.25',
    interestRate: '12.75',
    monthlyEmi: '23450',
    totalAmount: '844200',
    eligibleLoan: '700000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '7,00,000 BDT',
      minimumAmount: '1,00,000 BDT',
      maximumAmount: '20,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 23-60',
      offer: 'Special rate for women entrepreneurs',
      minimumIncome: 40000,
      minimumExperience: 1,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1.25% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'MUTUAL_TRUST_BANK_PLC' as const,
    amount: '350000',
    processingFee: '1.0',
    interestRate: '11.99',
    monthlyEmi: '11620',
    totalAmount: '418320',
    eligibleLoan: '350000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '3,50,000 BDT',
      minimumAmount: '30,000 BDT',
      maximumAmount: '10,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '6 Months',
      maximumYear: '4 Years',
    },
    eligibility: {
      condition: 'Salaried individuals, age 21-60',
      offer: 'Competitive rate for government employees',
      minimumIncome: 20000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'BANK_ASIA_PLC' as const,
    amount: '450000',
    processingFee: '1.5',
    interestRate: '13.25',
    monthlyEmi: '15250',
    totalAmount: '549000',
    eligibleLoan: '450000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '4,50,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '15,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 22-58',
      offer: 'Flexible repayment options',
      minimumIncome: 30000,
      minimumExperience: 1,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1.5% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'IFIC_BANK_PLC' as const,
    amount: '550000',
    processingFee: '1.0',
    interestRate: '12.25',
    monthlyEmi: '18350',
    totalAmount: '660600',
    eligibleLoan: '550000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '5,50,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '18,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 23-60',
      offer: 'Same-day approval for existing customers',
      minimumIncome: 35000,
      minimumExperience: 1,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'ONE_BANK_PLC' as const,
    amount: '250000',
    processingFee: '1.5',
    interestRate: '13.50',
    monthlyEmi: '8470',
    totalAmount: '304920',
    eligibleLoan: '250000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '2,50,000 BDT',
      minimumAmount: '25,000 BDT',
      maximumAmount: '8,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 21-57',
      offer: 'Easy approval for small loans',
      minimumIncome: 20000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1.5% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'MERCANTILE_BANK_PLC' as const,
    amount: '650000',
    processingFee: '1.25',
    interestRate: '12.75',
    monthlyEmi: '21780',
    totalAmount: '784080',
    eligibleLoan: '650000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '6,50,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '16,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried professionals, age 23-60',
      offer: 'Attractive rate for medical professionals',
      minimumIncome: 35000,
      minimumExperience: 1,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1.25% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'TRUST_BANK_PLC' as const,
    amount: '750000',
    processingFee: '1.0',
    interestRate: '12.00',
    monthlyEmi: '24900',
    totalAmount: '896400',
    eligibleLoan: '750000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '7,50,000 BDT',
      minimumAmount: '1,00,000 BDT',
      maximumAmount: '22,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 21-60',
      offer: 'Lowest processing fee in the market',
      minimumIncome: 40000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'AL_AARAFAH_ISLAMI_BANK_PLC' as const,
    amount: '400000',
    processingFee: '1.0',
    interestRate: '11.99',
    monthlyEmi: '13280',
    totalAmount: '478080',
    eligibleLoan: '400000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '4,00,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '12,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Shariah-compliant, age 22-60',
      offer: 'Islamic financing with zero interest (profit-based)',
      minimumIncome: 30000,
      minimumExperience: 1,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1% of financing amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '0% (Islamic compliant)',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue (charity fund)',
    },
  },
  {
    bankName: 'PREMIER_BANK_PLC' as const,
    amount: '350000',
    processingFee: '1.5',
    interestRate: '13.75',
    monthlyEmi: '11940',
    totalAmount: '429840',
    eligibleLoan: '350000',
    periodMonths: '36',
    loanType: 'PERSONAL_LOAN' as const,
    features: {
      loanAmount: '3,50,000 BDT',
      minimumAmount: '50,000 BDT',
      maximumAmount: '10,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '4 Years',
    },
    eligibility: {
      condition: 'Salaried individuals, age 21-57',
      offer: 'Quick processing with minimal paperwork',
      minimumIncome: 25000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1.5% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },

  // ── HOME_LOAN (10 entries) ──
  {
    bankName: 'SONALI_BANK_PLC' as const,
    amount: '3000000',
    processingFee: '0.5',
    interestRate: '9.50',
    monthlyEmi: '76450',
    totalAmount: '9174200',
    eligibleLoan: '3000000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '30,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '1,00,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '20 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen with valid income source',
      offer: 'Government rate with flexible tenure',
      minimumIncome: 80000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.5% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1% per month on overdue',
    },
  },
  {
    bankName: 'BRAC_BANK_PLC' as const,
    amount: '5000000',
    processingFee: '0.75',
    interestRate: '10.25',
    monthlyEmi: '66890',
    totalAmount: '8026800',
    eligibleLoan: '5000000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '50,00,000 BDT',
      minimumAmount: '10,00,000 BDT',
      maximumAmount: '2,00,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '2 Years',
      maximumYear: '25 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 25-60',
      offer: 'Lowest interest rate for green homes',
      minimumIncome: 100000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.75% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '0% after 2 years',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'DUTCH_BANGLA_BANK_PLC' as const,
    amount: '4000000',
    processingFee: '0.8',
    interestRate: '10.50',
    monthlyEmi: '53980',
    totalAmount: '6477600',
    eligibleLoan: '4000000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '40,00,000 BDT',
      minimumAmount: '8,00,000 BDT',
      maximumAmount: '1,50,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '20 Years',
    },
    eligibility: {
      condition: 'Salaried professionals, age 25-58',
      offer: 'Attractive rate for first-time home buyers',
      minimumIncome: 90000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.8% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '1.5% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'CITY_BANK_PLC' as const,
    amount: '6000000',
    processingFee: '0.6',
    interestRate: '9.99',
    monthlyEmi: '79320',
    totalAmount: '9518400',
    eligibleLoan: '6000000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '60,00,000 BDT',
      minimumAmount: '10,00,000 BDT',
      maximumAmount: '3,00,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '25 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 25-60',
      offer: 'Special rate for NRB customers',
      minimumIncome: 120000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.6% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1% per month on overdue',
    },
  },
  {
    bankName: 'EASTERN_BANK_PLC' as const,
    amount: '3500000',
    processingFee: '0.7',
    interestRate: '10.00',
    monthlyEmi: '46220',
    totalAmount: '5546400',
    eligibleLoan: '3500000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '35,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '2,00,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '2 Years',
      maximumYear: '20 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 23-60',
      offer: 'Up to 90% of property value financed',
      minimumIncome: 85000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.7% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '1.5% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'UNITED_COMMERCIAL_BANK_PLC' as const,
    amount: '4500000',
    processingFee: '0.75',
    interestRate: '10.75',
    monthlyEmi: '61450',
    totalAmount: '7374000',
    eligibleLoan: '4500000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '45,00,000 BDT',
      minimumAmount: '8,00,000 BDT',
      maximumAmount: '2,50,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '22 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 25-58',
      offer: 'Joint application allowed with spouse',
      minimumIncome: 100000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.75% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '1.5% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'IDLC_FINANCE_LIMITED' as const,
    amount: '5500000',
    processingFee: '0.65',
    interestRate: '10.25',
    monthlyEmi: '73580',
    totalAmount: '8829600',
    eligibleLoan: '5500000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '55,00,000 BDT',
      minimumAmount: '10,00,000 BDT',
      maximumAmount: '3,00,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '2 Years',
      maximumYear: '25 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 25-60',
      offer: 'Flexible structuring with construction loans',
      minimumIncome: 110000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.65% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '0% after 1 year',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1% per month on overdue',
    },
  },
  {
    bankName: 'IPDC_FINANCE_LIMITED' as const,
    amount: '2500000',
    processingFee: '0.8',
    interestRate: '11.00',
    monthlyEmi: '34370',
    totalAmount: '4124400',
    eligibleLoan: '2500000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '25,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '1,50,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '2 Years',
      maximumYear: '18 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 23-58',
      offer: 'Quick disbursement within 7 working days',
      minimumIncome: 75000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.8% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'BANGLADESH_DEVELOPMENT_BANK_PLC' as const,
    amount: '2000000',
    processingFee: '0.5',
    interestRate: '9.75',
    monthlyEmi: '26150',
    totalAmount: '3138000',
    eligibleLoan: '2000000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '20,00,000 BDT',
      minimumAmount: '3,00,000 BDT',
      maximumAmount: '80,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '20 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 21-60',
      offer: 'Lowest interest rate in the market',
      minimumIncome: 60000,
      minimumExperience: 2,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '0.5% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1% per month on overdue',
    },
  },
  {
    bankName: 'ISLAMI_BANK_BANGLADESH_PLC' as const,
    amount: '4800000',
    processingFee: '0.6',
    interestRate: '10.50',
    monthlyEmi: '64780',
    totalAmount: '7773600',
    eligibleLoan: '4800000',
    periodMonths: '120',
    loanType: 'HOME_LOAN' as const,
    features: {
      loanAmount: '48,00,000 BDT',
      minimumAmount: '8,00,000 BDT',
      maximumAmount: '2,50,00,000 BDT',
      loanTenure: '10 Years',
      minimumYear: '3 Years',
      maximumYear: '25 Years',
    },
    eligibility: {
      condition: 'Shariah-compliant customer, age 25-60',
      offer: 'Murabaha-based home financing',
      minimumIncome: 95000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.6% of financing amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '0% (Islamic compliant)',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1% per month on overdue (charity fund)',
    },
  },

  // ── CAR_LOAN (10 entries) ──
  {
    bankName: 'EASTERN_BANK_PLC' as const,
    amount: '1500000',
    processingFee: '1.0',
    interestRate: '11.75',
    monthlyEmi: '49720',
    totalAmount: '1789920',
    eligibleLoan: '1500000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '15,00,000 BDT',
      minimumAmount: '2,00,000 BDT',
      maximumAmount: '50,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Valid driving license, age 23-60',
      offer: '80% of car value financed',
      minimumIncome: 60000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'STANDARD_CHARTERED_BANK' as const,
    amount: '2500000',
    processingFee: '0.5',
    interestRate: '10.99',
    monthlyEmi: '81880',
    totalAmount: '2947680',
    eligibleLoan: '2500000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '25,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '75,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Premium banking customers, age 25-60',
      offer: 'Zero processing fee for priority customers',
      minimumIncome: 100000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.5% (waived for priority)',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'BRAC_BANK_PLC' as const,
    amount: '1800000',
    processingFee: '0.9',
    interestRate: '11.50',
    monthlyEmi: '59380',
    totalAmount: '2137680',
    eligibleLoan: '1800000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '18,00,000 BDT',
      minimumAmount: '3,00,000 BDT',
      maximumAmount: '60,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 23-60',
      offer: 'Reconditioned car financing available',
      minimumIncome: 70000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.9% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'DUTCH_BANGLA_BANK_PLC' as const,
    amount: '1200000',
    processingFee: '1.0',
    interestRate: '12.00',
    monthlyEmi: '39850',
    totalAmount: '1434600',
    eligibleLoan: '1200000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '12,00,000 BDT',
      minimumAmount: '2,00,000 BDT',
      maximumAmount: '40,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Valid driving license, age 22-58',
      offer: 'Used car financing at same rate',
      minimumIncome: 50000,
      minimumExperience: 2,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'CITY_BANK_PLC' as const,
    amount: '2200000',
    processingFee: '0.8',
    interestRate: '11.25',
    monthlyEmi: '72360',
    totalAmount: '2604960',
    eligibleLoan: '2200000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '22,00,000 BDT',
      minimumAmount: '4,00,000 BDT',
      maximumAmount: '70,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 23-60',
      offer: 'Instant approval for pre-approved customers',
      minimumIncome: 80000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.8% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'UNITED_COMMERCIAL_BANK_PLC' as const,
    amount: '1000000',
    processingFee: '1.2',
    interestRate: '12.50',
    monthlyEmi: '33400',
    totalAmount: '1202400',
    eligibleLoan: '1000000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '10,00,000 BDT',
      minimumAmount: '1,50,000 BDT',
      maximumAmount: '35,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Bangladeshi citizen, age 21-57',
      offer: 'Fast approval with minimal documentation',
      minimumIncome: 45000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1.2% of loan amount',
      earlySettlementFee: '5% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'MUTUAL_TRUST_BANK_PLC' as const,
    amount: '850000',
    processingFee: '1.0',
    interestRate: '12.25',
    monthlyEmi: '28280',
    totalAmount: '1018080',
    eligibleLoan: '850000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '8,50,000 BDT',
      minimumAmount: '1,00,000 BDT',
      maximumAmount: '30,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried individuals, age 22-60',
      offer: 'Competitive rate for energy-efficient cars',
      minimumIncome: 40000,
      minimumExperience: 1,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'PRIME_BANK_PLC' as const,
    amount: '2000000',
    processingFee: '0.9',
    interestRate: '11.75',
    monthlyEmi: '66300',
    totalAmount: '2386800',
    eligibleLoan: '2000000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '20,00,000 BDT',
      minimumAmount: '3,00,000 BDT',
      maximumAmount: '55,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 23-60',
      offer: 'Special discount for hybrid cars',
      minimumIncome: 75000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.9% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'IFIC_BANK_PLC' as const,
    amount: '1600000',
    processingFee: '1.0',
    interestRate: '12.00',
    monthlyEmi: '53140',
    totalAmount: '1913040',
    eligibleLoan: '1600000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '16,00,000 BDT',
      minimumAmount: '2,50,000 BDT',
      maximumAmount: '45,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '5 Years',
    },
    eligibility: {
      condition: 'Valid driving license, age 23-58',
      offer: 'Insurance included in financing package',
      minimumIncome: 60000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '750 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'IPDC_FINANCE_LIMITED' as const,
    amount: '3000000',
    processingFee: '0.7',
    interestRate: '11.25',
    monthlyEmi: '98680',
    totalAmount: '3552480',
    eligibleLoan: '3000000',
    periodMonths: '36',
    loanType: 'CAR_LOAN' as const,
    features: {
      loanAmount: '30,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '80,00,000 BDT',
      loanTenure: '3 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Salaried/business, age 25-60',
      offer: 'Luxury car financing available',
      minimumIncome: 120000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.7% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },

  // ── SME_LOAN (10 entries) ──
  {
    bankName: 'IDLC_FINANCE_LIMITED' as const,
    amount: '10000000',
    processingFee: '1.0',
    interestRate: '14.00',
    monthlyEmi: '332650',
    totalAmount: '19959000',
    eligibleLoan: '10000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '1,00,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '5,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '10 Years',
    },
    eligibility: {
      condition: 'Registered business operating 2+ years',
      offer: 'Flexible repayment based on business cash flow',
      minimumIncome: 200000,
      minimumExperience: 2,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '2000 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'ISLAMI_BANK_BANGLADESH_PLC' as const,
    amount: '5000000',
    processingFee: '0.8',
    interestRate: '13.50',
    monthlyEmi: '168080',
    totalAmount: '10084800',
    eligibleLoan: '5000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '50,00,000 BDT',
      minimumAmount: '3,00,000 BDT',
      maximumAmount: '3,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '7 Years',
    },
    eligibility: {
      condition: 'Shariah-compliant business, age 25-60',
      offer: 'Profit & loss sharing model available',
      minimumIncome: 150000,
      minimumExperience: 2,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.8% of financing amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1.5% per month on overdue (charity fund)',
    },
  },
  {
    bankName: 'BRAC_BANK_PLC' as const,
    amount: '8000000',
    processingFee: '0.9',
    interestRate: '13.75',
    monthlyEmi: '264750',
    totalAmount: '15885000',
    eligibleLoan: '8000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '80,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '4,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '8 Years',
    },
    eligibility: {
      condition: 'Registered SME with 2+ years track record',
      offer: 'Women entrepreneur special rate 12.50%',
      minimumIncome: 180000,
      minimumExperience: 2,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.9% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'EASTERN_BANK_PLC' as const,
    amount: '6000000',
    processingFee: '1.0',
    interestRate: '14.25',
    monthlyEmi: '200400',
    totalAmount: '12024000',
    eligibleLoan: '6000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '60,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '3,50,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '8 Years',
    },
    eligibility: {
      condition: 'SME with valid trade license, age 23-60',
      offer: 'Collateral-free loan up to 20 lakh',
      minimumIncome: 160000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'CITY_BANK_PLC' as const,
    amount: '12000000',
    processingFee: '0.8',
    interestRate: '13.25',
    monthlyEmi: '392380',
    totalAmount: '23542800',
    eligibleLoan: '12000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '1,20,00,000 BDT',
      minimumAmount: '10,00,000 BDT',
      maximumAmount: '6,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '10 Years',
    },
    eligibility: {
      condition: 'Established SME with growth potential',
      offer: 'Working capital and term loan combo',
      minimumIncome: 250000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.8% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '1.5% of prepaid amount',
      LoanReSchedulingFee: '2000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'UNITED_COMMERCIAL_BANK_PLC' as const,
    amount: '3500000',
    processingFee: '1.2',
    interestRate: '14.50',
    monthlyEmi: '117490',
    totalAmount: '7049400',
    eligibleLoan: '3500000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '35,00,000 BDT',
      minimumAmount: '3,00,000 BDT',
      maximumAmount: '2,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '7 Years',
    },
    eligibility: {
      condition: 'SME with minimum 1 year operation',
      offer: 'Startup-friendly financing available',
      minimumIncome: 120000,
      minimumExperience: 1,
      ageRequirement: 22,
    },
    feesCharges: {
      processingFee: '1.2% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '3% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'IPDC_FINANCE_LIMITED' as const,
    amount: '15000000',
    processingFee: '0.7',
    interestRate: '12.99',
    monthlyEmi: '477450',
    totalAmount: '28647000',
    eligibleLoan: '15000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '1,50,00,000 BDT',
      minimumAmount: '10,00,000 BDT',
      maximumAmount: '8,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '12 Years',
    },
    eligibility: {
      condition: 'Growth-stage SME, age 25-60',
      offer: 'Equipment financing with low margin',
      minimumIncome: 300000,
      minimumExperience: 3,
      ageRequirement: 25,
    },
    feesCharges: {
      processingFee: '0.7% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '2000 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },
  {
    bankName: 'LANKABANGLA_FINANCE_LIMITED' as const,
    amount: '4500000',
    processingFee: '1.0',
    interestRate: '14.00',
    monthlyEmi: '149690',
    totalAmount: '8981400',
    eligibleLoan: '4500000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '45,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '2,50,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '7 Years',
    },
    eligibility: {
      condition: 'SME with valid business registration',
      offer: 'Fast disbursement for urgent business needs',
      minimumIncome: 140000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'MIDAS_FINANCING_LIMITED' as const,
    amount: '2500000',
    processingFee: '1.0',
    interestRate: '14.75',
    monthlyEmi: '84020',
    totalAmount: '5041200',
    eligibleLoan: '2500000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '25,00,000 BDT',
      minimumAmount: '2,00,000 BDT',
      maximumAmount: '1,50,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '6 Years',
    },
    eligibility: {
      condition: 'Small business with 1+ year operation',
      offer: 'Micro SME financing with easy terms',
      minimumIncome: 80000,
      minimumExperience: 1,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '1% of loan amount',
      earlySettlementFee: '4% of outstanding',
      prepaymentFee: '2.5% of prepaid amount',
      LoanReSchedulingFee: '1000 BDT',
      penalCharge: '2% per month on overdue',
    },
  },
  {
    bankName: 'SABINCO' as const,
    amount: '7000000',
    processingFee: '0.8',
    interestRate: '13.50',
    monthlyEmi: '235310',
    totalAmount: '14118600',
    eligibleLoan: '7000000',
    periodMonths: '60',
    loanType: 'SME_LOAN' as const,
    features: {
      loanAmount: '70,00,000 BDT',
      minimumAmount: '5,00,000 BDT',
      maximumAmount: '3,00,00,000 BDT',
      loanTenure: '5 Years',
      minimumYear: '1 Year',
      maximumYear: '8 Years',
    },
    eligibility: {
      condition: 'SME with good credit history, age 23-60',
      offer: 'Supply chain financing solutions',
      minimumIncome: 175000,
      minimumExperience: 2,
      ageRequirement: 23,
    },
    feesCharges: {
      processingFee: '0.8% of loan amount',
      earlySettlementFee: '3% of outstanding',
      prepaymentFee: '2% of prepaid amount',
      LoanReSchedulingFee: '1500 BDT',
      penalCharge: '1.5% per month on overdue',
    },
  },

  // ── INSTANT_LOAN (6 entries) ──
  {
    bankName: 'FINUPS_AGRIM' as const,
    amount: '50000',
    processingFee: '0',
    interestRate: '18.00',
    monthlyEmi: '4550',
    totalAmount: '54600',
    eligibleLoan: '50000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '50,000 BDT',
      minimumAmount: '5,000 BDT',
      maximumAmount: '2,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '3 Months',
      maximumYear: '2 Years',
    },
    eligibility: {
      condition: 'Any Bangladeshi citizen with valid NID, age 18-65',
      offer: 'No paperwork, instant disbursement',
      minimumIncome: 10000,
      minimumExperience: 0,
      ageRequirement: 18,
    },
    feesCharges: {
      processingFee: 'Zero processing fee',
      earlySettlementFee: 'No early settlement fee',
      prepaymentFee: 'No prepayment fee',
      LoanReSchedulingFee: '300 BDT',
      penalCharge: '3% per month on overdue',
    },
  },
  {
    bankName: 'BRAC_BANK_PLC' as const,
    amount: '100000',
    processingFee: '0',
    interestRate: '16.50',
    monthlyEmi: '9030',
    totalAmount: '108360',
    eligibleLoan: '100000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '1,00,000 BDT',
      minimumAmount: '10,000 BDT',
      maximumAmount: '5,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '3 Months',
      maximumYear: '3 Years',
    },
    eligibility: {
      condition: 'Existing BRAC bank account holders',
      offer: 'Instant approval via mobile app',
      minimumIncome: 15000,
      minimumExperience: 0,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: 'Zero processing fee',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2.5% per month on overdue',
    },
  },
  {
    bankName: 'CITY_BANK_PLC' as const,
    amount: '150000',
    processingFee: '0',
    interestRate: '17.00',
    monthlyEmi: '13680',
    totalAmount: '164160',
    eligibleLoan: '150000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '1,50,000 BDT',
      minimumAmount: '10,000 BDT',
      maximumAmount: '4,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '3 Months',
      maximumYear: '2 Years',
    },
    eligibility: {
      condition: 'City Bank app users, age 21-60',
      offer: 'Instant cash in 5 minutes',
      minimumIncome: 12000,
      minimumExperience: 0,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: 'Zero processing fee',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '3% per month on overdue',
    },
  },
  {
    bankName: 'DUTCH_BANGLA_BANK_PLC' as const,
    amount: '80000',
    processingFee: '0',
    interestRate: '17.50',
    monthlyEmi: '7320',
    totalAmount: '87840',
    eligibleLoan: '80000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '80,000 BDT',
      minimumAmount: '5,000 BDT',
      maximumAmount: '3,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '3 Months',
      maximumYear: '2 Years',
    },
    eligibility: {
      condition: 'DBBL Nexus cardholders, age 21-60',
      offer: 'Pre-approved loan based on card usage',
      minimumIncome: 15000,
      minimumExperience: 0,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: 'Zero processing fee',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '300 BDT',
      penalCharge: '3% per month on overdue',
    },
  },
  {
    bankName: 'NAGAD_FINANCE_PLC' as const,
    amount: '30000',
    processingFee: '0',
    interestRate: '18.50',
    monthlyEmi: '2750',
    totalAmount: '33000',
    eligibleLoan: '30000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '30,000 BDT',
      minimumAmount: '2,000 BDT',
      maximumAmount: '1,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '1 Month',
      maximumYear: '1 Year',
    },
    eligibility: {
      condition: 'Active Nagad wallet user, age 18-65',
      offer: 'Loan directly to Nagad wallet',
      minimumIncome: 5000,
      minimumExperience: 0,
      ageRequirement: 18,
    },
    feesCharges: {
      processingFee: 'Zero processing fee',
      earlySettlementFee: 'No early settlement fee',
      prepaymentFee: 'No prepayment fee',
      LoanReSchedulingFee: '200 BDT',
      penalCharge: '3% per month on overdue',
    },
  },
  {
    bankName: 'BANK_ASIA_PLC' as const,
    amount: '200000',
    processingFee: '0.5',
    interestRate: '16.00',
    monthlyEmi: '18120',
    totalAmount: '217440',
    eligibleLoan: '200000',
    periodMonths: '12',
    loanType: 'INSTANT_LOAN' as const,
    features: {
      loanAmount: '2,00,000 BDT',
      minimumAmount: '20,000 BDT',
      maximumAmount: '6,00,000 BDT',
      loanTenure: '1 Year',
      minimumYear: '6 Months',
      maximumYear: '3 Years',
    },
    eligibility: {
      condition: 'Existing Bank Asia account holders',
      offer: 'Digital KYC, no branch visit needed',
      minimumIncome: 20000,
      minimumExperience: 0,
      ageRequirement: 21,
    },
    feesCharges: {
      processingFee: '0.5% of loan amount',
      earlySettlementFee: '2% of outstanding',
      prepaymentFee: '1% of prepaid amount',
      LoanReSchedulingFee: '500 BDT',
      penalCharge: '2.5% per month on overdue',
    },
  },
];

export const seedLoans = async () => {
  try {
    for (const loan of loanSeedData) {
      const { features, eligibility, feesCharges, ...loanData } = loan;

      await prisma.loan.upsert({
        where: {
          id: `${loanData.bankName}_${loanData.loanType}`,
        },
        update: {
          ...loanData,
          isActive: true,
          features: {
            upsert: {
              create: features,
              update: features,
            },
          },
          eligibility: {
            upsert: {
              create: eligibility,
              update: eligibility,
            },
          },
          feesCharges: {
            upsert: {
              create: feesCharges,
              update: feesCharges,
            },
          },
        },
        create: {
          id: `${loanData.bankName}_${loanData.loanType}`,
          ...loanData,
          isActive: true,
          features: { create: features },
          eligibility: { create: eligibility },
          feesCharges: { create: feesCharges },
        },
      });
    }

    console.log(`✅ ${loanSeedData.length} loans seeded successfully`);
    logger.info(`${loanSeedData.length} loans upserted successfully`);
  } catch (error) {
    logger.error(`Loan seeding failed: ${error}`);
    throw error;
  }
};
